site_name: Python Eledio library
nav:
    - Home: index.md
    - API description: api_description.md
    - Application example: application_example.md
    - Contact: contact.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
copyright: Eledio Â© 2019
site_description: Documentation site of Python Eledio library
